import { Poppins, Karla } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';

const poppins = Poppins({
  weight: ['400', '700'], // You can add more weights as needed
  variable: '--font-poppins',
  subsets: ['latin'], // You can customize the subsets
});

const karla = Karla({
  weight: ['400', '700'], // Add the weights you need
  variable: '--font-karla',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${karla.variable}`}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#E73725', 
            },
          }}
        >
          <AntdRegistry>{children}</AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
